### PR TITLE
eslint-prettier-airbnb dev deps added

### PR DESCRIPTION
**Pull request by hampusolsen**
Added eslint, prettier & airbnb configs/dependencies.

### CODE REVIEW

**Comment by Danielwestin** [comment]
approved

**Comment by rubikuo** [comment]
ser bra ut

**Review by danielReineborn — APPROVED** [review]
lgtm - looks good to me!

**Comment by MohammedMotar00** [comment]
hej

**Comment by oskarhertzman** [comment]
nice!

**Review by Danielwestin — COMMENTED** [review]
approved

**Review by rubikuo — APPROVED** [review]

**Review by oskarhertzman — COMMENTED** [review]
approved

**Pull request merged**
